# =========== Copyright 2023 @ CAMEL-AI.org. All Rights Reserved. ===========
# Licensed under the Apache License, Version 2.0 (the “License”);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an “AS IS” BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# =========== Copyright 2023 @ CAMEL-AI.org. All Rights Reserved. ===========
from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import TYPE_CHECKING, Optional, Sequence,List

from openai._types import NOT_GIVEN, NotGiven

from camel.configs.base_config import BaseConfig

if TYPE_CHECKING:
    from camel.functions import OpenAIFunction


@dataclass(frozen=True)
class ChatGPTConfig(BaseConfig):
    r"""Defines the parameters for generating chat completions using the
    OpenAI API.

    Args:
        temperature (float, optional): Sampling temperature to use, between
            :obj:`0` and :obj:`2`. Higher values make the output more random,
            while lower values make it more focused and deterministic.
            (default: :obj:`0.2`)
        top_p (float, optional): An alternative to sampling with temperature,
            called nucleus sampling, where the model considers the results of
            the tokens with top_p probability mass. So :obj:`0.1` means only
            the tokens comprising the top 10% probability mass are considered.
            (default: :obj:`1.0`)
        n (int, optional): How many chat completion choices to generate for
            each input message. (default: :obj:`1`)
        stream (bool, optional): If True, partial message deltas will be sent
            as data-only server-sent events as they become available.
            (default: :obj:`False`)
        stop (str or list, optional): Up to :obj:`4` sequences where the API
            will stop generating further tokens. (default: :obj:`None`)
        max_tokens (int, optional): The maximum number of tokens to generate
            in the chat completion. The total length of input tokens and
            generated tokens is limited by the model's context length.
            (default: :obj:`None`)
        presence_penalty (float, optional): Number between :obj:`-2.0` and
            :obj:`2.0`. Positive values penalize new tokens based on whether
            they appear in the text so far, increasing the model's likelihood
            to talk about new topics. See more information about frequency and
            presence penalties. (default: :obj:`0.0`)
        frequency_penalty (float, optional): Number between :obj:`-2.0` and
            :obj:`2.0`. Positive values penalize new tokens based on their
            existing frequency in the text so far, decreasing the model's
            likelihood to repeat the same line verbatim. See more information
            about frequency and presence penalties. (default: :obj:`0.0`)
        logit_bias (dict, optional): Modify the likelihood of specified tokens
            appearing in the completion. Accepts a json object that maps tokens
            (specified by their token ID in the tokenizer) to an associated
            bias value from :obj:`-100` to :obj:`100`. Mathematically, the bias
            is added to the logits generated by the model prior to sampling.
            The exact effect will vary per model, but values between:obj:` -1`
            and :obj:`1` should decrease or increase likelihood of selection;
            values like :obj:`-100` or :obj:`100` should result in a ban or
            exclusive selection of the relevant token. (default: :obj:`{}`)
        user (str, optional): A unique identifier representing your end-user,
            which can help OpenAI to monitor and detect abuse.
            (default: :obj:`""`)
        tools (list[OpenAIFunction], optional): A list of tools the model may
            call. Currently, only functions are supported as a tool. Use this
            to provide a list of functions the model may generate JSON inputs
            for. A max of 128 functions are supported.
        tool_choice (Union[dict[str, str], str], optional): Controls which (if
            any) tool is called by the model. :obj:`"none"` means the model
            will not call any tool and instead generates a message.
            :obj:`"auto"` means the model can pick between generating a
            message or calling one or more tools.  :obj:`"required"` means the
            model must call one or more tools. Specifying a particular tool
            via {"type": "function", "function": {"name": "my_function"}}
            forces the model to call that tool. :obj:`"none"` is the default
            when no tools are present. :obj:`"auto"` is the default if tools
            are present.
    """

    temperature: float = 0.2  # openai default: 1.0
    top_p: float = 1.0
    n: int = 1
    stream: bool = False
    stop: str | Sequence[str] | NotGiven = NOT_GIVEN
    max_tokens: int | NotGiven = NOT_GIVEN
    presence_penalty: float = 0.0
    frequency_penalty: float = 0.0
    logit_bias: dict = field(default_factory=dict)
    user: str = ""
    tools: Optional[list[OpenAIFunction]] = None
    tool_choice: Optional[dict[str, str] | str] = None

    def __post_init__(self):
        if self.tools is not None:
            object.__setattr__(
                self,
                'tools',
                [tool.get_openai_tool_schema() for tool in self.tools],
            )


OPENAI_API_PARAMS = {param for param in asdict(ChatGPTConfig()).keys()}


@dataclass(frozen=True)
class OpenSourceConfig(BaseConfig):
    r"""Defines parameters for setting up open-source models and includes
    parameters to be passed to chat completion function of OpenAI API.

    Args:
        model_path (str): The path to a local folder containing the model
            files or the model card in HuggingFace hub.
        server_url (str): The URL to the server running the model inference
            which will be used as the API base of OpenAI API.
        api_params (ChatGPTConfig): An instance of :obj:ChatGPTConfig to
            contain the arguments to be passed to OpenAI API.
    """

    model_path: str
    server_url: str
    api_params: ChatGPTConfig = field(default_factory=ChatGPTConfig)

@dataclass(frozen=True)
class ZhipuaiConfig(BaseConfig):
    r"""
    Defines the configuration parameters for the ZhipuAI API.

    Args:
        model (str): **Required**. The model encoding to be used for the API call.
            This specifies the model version or type that the API will utilize.
        messages (List[Dict[str, Any]]): **Required**. A list of messages that 
            contain the conversation history to be used as context for the AI's response.
            Each message is a dictionary with "role" and "content" keys, where "role"
            can be "system", "user", "assistant", or "tool", and "content" is the text of the message.
            - request_id (str, optional): A unique identifier for the request, which 
            is useful for tracking and should be unique for each call. If not provided,
            the platform will generate one by default.
        do_sample (bool, optional): Determines whether to use sampling strategy 
            when generating the response. If set to false, the temperature and top_p 
            parameters will not affect the sampling process. Defaults to True.
        stream (bool, optional): If set to true, the model will return its 
            generated content in chunks via an Event Stream. This is useful for 
            receiving partial results before the full response is complete. 
            Defaults to False, meaning the response will be returned all at once.
        temperature (float, optional): Controls the randomness of the output. A 
            value between 0.0 and 1.0, where higher values result in more randomness 
            and lower values result in more focused responses. Defaults to 0.95.
        top_p (float, optional): Another sampling method known as nucleus sampling,
            where the model considers the tokens with the highest probabilities. 
            A value between 0.0 and 1.0, but not 0 or 1. The default is 0.7.
        max_tokens (int, optional): The maximum number of tokens to generate 
            in the response. The total length of input and generated text is 
            constrained by the model's context length. Defaults to 1024.
        stop (List[str], optional): A list of stop words that, when encountered, 
            will cause the model to stop generating further tokens. Currently, only 
            a single stop word is supported.
        tools (List[str], optional): A list of tools that the model can utilize 
            to assist in generating the response. The default tool is "web_search".
        tool_choice (str, optional): Controls how the model selects which function 
            to call when using tools. The default is "auto", which allows the model 
            to decide.
        user_id (str, optional): A unique identifier for the end user, which 
            assists the platform in monitoring and intervening in cases of abuse or 
            generation of inappropriate content. The ID should be between 6 and 128 
            characters in length.
    """

    request_id: Optional[str] = None
    do_sample: Optional[bool] = True
    stream: Optional[bool] = False
    temperature: Optional[float] = 0.95
    top_p: Optional[float] = 0.7
    max_tokens: Optional[int] = 1024
    stop: Optional[List[str]] = None
    tools: Optional[List[str]] = None
    tool_choice: Optional[str] = "auto"
    user_id: Optional[str] = None

ZHIPU_API_PARAMS = {param for param in asdict(ZhipuaiConfig()).keys()}