
from enum import Enum


class TaskEventType(Enum):
    TASK_CREATED = "TASK_CREATED"
    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    TASK_DECOMPOSED = "TASK_DECOMPOSED"
    TASK_ARCHIVED = "TASK_ARCHIVED"
    TASK_REASSIGNED = "TASK_REASSIGNED"