token: "traceroot-8a344d685a6e4ab985d50736a944517e"
service_name: "camel-example"
github_owner: "camel-ai"
github_repo_name: "camel"
github_commit_hash: "master"
otlp_endpoint: "http://3.23.162.117:4318/v1/traces"
