haiku_b_instruction = (
    "Can you write me a haiku? A haiku is a poem that consists of three phrases composed of 17 syllables in a 5, 7, 5 pattern.",
    "Could you pen a haiku for me? It's a type of poem with three lines, following a 5, 7, 5 syllable pattern.",
    "Would you be able to compose a haiku for me? This is a poem with three lines, each with a specific number of syllables: 5, 7, and 5.",
    "Can you create a haiku? It's a three-line poem with a total of 17 syllables, distributed in a 5, 7, 5 pattern.",
    "Are you able to draft a haiku for me? It's a poem that has three lines and 17 syllables, arranged in a 5, 7, 5 pattern.",
    "Could you craft a haiku? This is a poem that has three lines and follows a 5, 7, 5 syllable pattern.",
    "Would you mind writing a haiku for me? It's a three-line poem with a 5, 7, 5 syllable count.",
    "Can you put together a haiku? It's a poem with three lines, each having 5, 7, and 5 syllables respectively.",
    "Are you capable of writing a haiku for me? It's a poem that consists of three lines with a 5, 7, 5 syllable pattern.",
    "Could you construct a haiku? It's a poem that has three lines and 17 syllables, in a 5, 7, 5 arrangement.",
    "Would you be willing to write a haiku for me? It's a three-line poem with a 5, 7, 5 syllable structure.",
    "Are you able to generate a haiku for me? It's a poem that has three lines and 17 syllables, arranged in a 5, 7, 5 pattern.",
    "Could you produce a haiku? This is a poem that has three lines and follows a 5, 7, 5 syllable pattern.",
    "Would you consider writing a haiku for me? It's a three-line poem with a 5, 7, 5 syllable count.",
    "Can you compose a haiku? It's a poem with three lines, each having 5, 7, and 5 syllables respectively.",
    "Are you proficient in writing a haiku for me? It's a poem that consists of three lines with a 5, 7, 5 syllable pattern.",
    "Could you devise a haiku? It's a poem that has three lines and 17 syllables, in a 5, 7, 5 arrangement.",
    "Would you be interested in writing a haiku for me? It's a three-line poem with a 5, 7, 5 syllable structure.",
    "Can you create a haiku? It's a poem with three lines, each with a specific number of syllables: 5, 7, and 5.",
    "Are you able to author a haiku for me? It's a poem that has three lines and 17 syllables, arranged in a 5, 7, 5 pattern.",
)

tanka_b_instruction = (
    "Can you write me a Tanka? A Tanka is a poem that consists of five lines composed of syllables in a 5-7-5-7-7 pattern.",
    "Could you compose a Tanka for me? It's a five-line poem with a syllable pattern of 5-7-5-7-7.",
    "Would you be able to draft a Tanka? This is a type of poem that has five lines and follows a 5-7-5-7-7 syllable structure.",
    "Can you create a Tanka for me? It's a poem with five lines, each line having a syllable count of 5, 7, 5, 7, and 7 respectively.",
    "Are you able to pen a Tanka? It's a five-line poem with a syllable pattern of 5-7-5-7-7.",
    "Could you put together a Tanka for me? It's a poem that follows a 5-7-5-7-7 syllable pattern across five lines.",
    "Would you mind writing a Tanka? It's a poem that has five lines and a syllable count of 5-7-5-7-7.",
    "Can you craft a Tanka for me? It's a five-line poem that adheres to a 5-7-5-7-7 syllable structure.",
    "Are you capable of composing a Tanka? It's a poem with five lines and a syllable pattern of 5-7-5-7-7.",
    "Could you construct a Tanka for me? It's a poem that consists of five lines with a syllable count of 5-7-5-7-7.",
    "Would you be willing to write a Tanka? It's a five-line poem that follows a 5-7-5-7-7 syllable pattern.",
    "Are you able to create a Tanka? It's a poem that consists of five lines with a syllable count of 5-7-5-7-7.",
    "Could you generate a Tanka for me? It's a five-line poem that follows a 5-7-5-7-7 syllable pattern.",
    "Would you consider writing a Tanka? It's a poem with five lines and a syllable structure of 5-7-5-7-7.",
    "Can you produce a Tanka for me? It's a poem that consists of five lines with a syllable count of 5-7-5-7-7.",
    "Are you able to draft a Tanka? It's a five-line poem that follows a 5-7-5-7-7 syllable pattern.",
    "Could you devise a Tanka for me? It's a poem with five lines and a syllable structure of 5-7-5-7-7.",
    "Would you be able to create a Tanka? It's a poem that consists of five lines with a syllable count of 5-7-5-7-7.",
    "Can you design a Tanka for me? It's a five-line poem that follows a 5-7-5-7-7 syllable pattern.",
    "Are you capable of writing a Tanka? It's a poem with five lines and a syllable structure of 5-7-5-7-7.",
)

line_syllable_constrained_poem_b_instruction = (
    "Can you write me a poem? It should have {k} lines. The number of syllables for the lines in the poem should follow a {pattern} pattern.",
    "Could you compose a poem for me? It needs to be {k} lines long and the syllable count for each line should match a {pattern} pattern.",
    "Would you be able to pen a poem for me? It must consist of {k} lines and the syllable count for each line should adhere to a {pattern} pattern.",
    "Can you craft a poem for me? It should contain {k} lines and the syllable count for each line should conform to a {pattern} pattern.",
    "Are you able to create a poem for me? It needs to have {k} lines and the syllable count for each line should follow a {pattern} pattern.",
    "Could you draft a poem for me? It should be {k} lines long and the syllable count for each line should align with a {pattern} pattern.",
    "Would you mind writing a poem for me? It should consist of {k} lines and the syllable count for each line should fit a {pattern} pattern.",
    "Are you capable of writing a poem for me? It should be {k} lines long and the syllable count for each line should match a {pattern} pattern.",
    "Could you construct a poem for me? It should have {k} lines and the syllable count for each line should follow a {pattern} pattern.",
    "Would you be willing to write a poem for me? It should be {k} lines long and the syllable count for each line should adhere to a {pattern} pattern.",
    "Can you devise a poem for me? It should contain {k} lines and the syllable count for each line should conform to a {pattern} pattern.",
    "Are you able to author a poem for me? It needs to have {k} lines and the syllable count for each line should follow a {pattern} pattern.",
    "Could you generate a poem for me? It should be {k} lines long and the syllable count for each line should align with a {pattern} pattern.",
    "Would you consider writing a poem for me? It should consist of {k} lines and the syllable count for each line should fit a {pattern} pattern.",
    "Can you produce a poem for me? It should be made up of {k} lines and the syllable count for each line should correspond to a {pattern} pattern.",
    "Are you competent to write a poem for me? It should be {k} lines long and the syllable count for each line should match a {pattern} pattern.",
    "Could you create a poem for me? It should have {k} lines and the syllable count for each line should follow a {pattern} pattern.",
    "Would you be up for writing a poem for me? It should be {k} lines long and the syllable count for each line should adhere to a {pattern} pattern.",
    "Can you design a poem for me? It should contain {k} lines and the syllable count for each line should conform to a {pattern} pattern.",
    "Are you prepared to write a poem for me? It needs to have {k} lines and the syllable count for each line should follow a {pattern} pattern.",
)

syllable_constrained_poem_b_instruction = (
    "Can you produce a short poem where each line has {syllable} syllables?",
    "Is it possible for you to write a short poem, each line containing {syllable} syllables?",
    "Can you compose a short poem where every line consists of {syllable} syllables?",
    "Are you able to craft a short poem with each line having {syllable} syllables?",
    "Can you construct a short poem where each line is made up of {syllable} syllables?",
    "Could you put together a short poem where every line has {syllable} syllables?",
    "Can you devise a short poem with each line containing {syllable} syllables?",
    "Are you capable of creating a short poem where each line has {syllable} syllables?",
    "Can you generate a short poem where every line consists of {syllable} syllables?",
    "Can you draft a short poem where each line is made up of {syllable} syllables?",
    "Are you able to design a short poem where every line has {syllable} syllables?",
    "Can you pen a short poem with each line containing {syllable} syllables?",
    "Could you author a short poem where each line consists of {syllable} syllables?",
    "Can you script a short poem where each line has {syllable} syllables?",
    "Are you capable of penning a short poem with each line having {syllable} syllables?",
    "Can you write up a short poem where every line is made up of {syllable} syllables?",
    "Could you jot down a short poem where each line contains {syllable} syllables?",
    "Can you scribe a short poem where every line consists of {syllable} syllables?",
    "Are you able to inscribe a short poem with each line having {syllable} syllables?",
)

r_feedback_neg = (
    "The generated {form_name} is incorrect.",
    "The {form_name} that was created is not correct.",
    "The produced {form_name} is wrong.",
    "The {form_name} that has been generated is not right.",
    "The {form_name} that was produced is not accurate.",
    "The created {form_name} is not correct.",
    "The {form_name} that was formed is wrong.",
    "The {form_name} that was developed is not right.",
    "The {form_name} that was built is incorrect.",
    "The {form_name} that was constructed is wrong.",
    "The {form_name} that was assembled is not right.",
    "The {form_name} that was composed is incorrect.",
    "The {form_name} that was devised is not accurate.",
    "The {form_name} that was written is not right.",
)

r_feedback_pos = (
    "The generated {form_name} is correct. Congrats! You have successfully produced a poem that matches the assignment description.",
    "Well done! The {form_name} you've created is accurate and fits the assignment description.",
    "Congratulations! You've successfully crafted a poem that aligns with the assignment description. The {form_name} you've generated is correct.",
    "You've done a great job! The poem you've created matches the assignment description and the {form_name} is correct.",
    "Good job! You've successfully made a poem that fits the assignment description. The {form_name} you've generated is right.",
    "Bravo! The {form_name} you've produced is correct and matches the assignment description.",
    "You've nailed it! The poem you've created aligns with the assignment description and the {form_name} you've generated is correct.",
    "Well done! You've successfully created a poem that fits the assignment description. The {form_name} you've generated is accurate.",
    "Great work! The {form_name} you've produced is correct and aligns with the assignment description.",
    "Congratulations! The {form_name} you've generated is correct and your poem matches the assignment description.",
    "You've done it! The poem you've created fits the assignment description and the {form_name} you've generated is correct.",
    "Good job! The {form_name} you've produced is accurate and your poem matches the assignment description.",
    "Bravo! You've successfully crafted a poem that aligns with the assignment description. The {form_name} you've generated is right.",
    "You've nailed it! The {form_name} you've produced is correct and your poem fits the assignment description.",
    "Well done! The poem you've created matches the assignment description and the {form_name} you've generated is accurate.",
    "Great work! You've successfully made a poem that fits the assignment description. The {form_name} you've generated is right.",
    "Congratulations! The poem you've created aligns with the assignment description and the {form_name} you've produced is correct.",
    "You've done it! The {form_name} you've generated is accurate and your poem matches the assignment description.",
    "Good job! The poem you've created fits the assignment description and the {form_name} you've produced is correct.",
    "Bravo! The {form_name} you've generated is right and your poem matches the assignment description.",
    "You've nailed it! You've successfully created a poem that aligns with the assignment description. The {form_name} you've produced is correct.",
)

line_number_fp_feedback = (
    "Write a {form_name} that has exactly {syllable_req_len} lines. Write {improv_direction} lines.",
    "Compose a {form_name} with precisely {syllable_req_len} lines. {improv_direction} lines should be written.",
    "Create a {form_name} that consists of {syllable_req_len} lines. Make sure to write {improv_direction} lines.",
    "Your task is to write a {form_name} that contains exactly {syllable_req_len} lines. There should be {improv_direction} lines.",
    "Draft a {form_name} with a total of {syllable_req_len} lines. {improv_direction} lines need to be written.",
    "Pen a {form_name} that should have {syllable_req_len} lines. {improv_direction} lines must be written.",
    "Construct a {form_name} that includes {syllable_req_len} lines. {improv_direction} lines should be written.",
    "Develop a {form_name} that is made up of {syllable_req_len} lines. Write {improv_direction} lines.",
    "Design a {form_name} that has {syllable_req_len} lines in total. Write {improv_direction} lines.",
    "Craft a {form_name} that should consist of {syllable_req_len} lines. {improv_direction} lines need to be written.",
    "Put together a {form_name} that includes exactly {syllable_req_len} lines. Write {improv_direction} lines.",
    "Generate a {form_name} that contains {syllable_req_len} lines. {improv_direction} lines should be written.",
    "Produce a {form_name} that has {syllable_req_len} lines. Write {improv_direction} lines.",
    "Create a {form_name} that should have {syllable_req_len} lines. {improv_direction} lines must be written.",
    "Compose a {form_name} that includes {syllable_req_len} lines. Write {improv_direction} lines.",
    "Your task is to draft a {form_name} with {syllable_req_len} lines. {improv_direction} lines should be written.",
    "Make a {form_name} that consists of {syllable_req_len} lines. Write {improv_direction} lines.",
    "Your job is to write a {form_name} that contains {syllable_req_len} lines. {improv_direction} lines should be written.",
    "Form a {form_name} that has {syllable_req_len} lines. Write {improv_direction} lines.",
    "Your assignment is to create a {form_name} with {syllable_req_len} lines. {improv_direction} lines should be written.",
)

line_number_fn_feedback = (
    "Do not write a {form_name} that has more or less lines than {syllable_req_len}.",
    "Ensure that your {form_name} does not have more or fewer lines than {syllable_req_len}.",
    "Your {form_name} should not contain more or less lines than {syllable_req_len}.",
    "The {form_name} you write should not exceed or fall short of {syllable_req_len} lines.",
    "Avoid writing a {form_name} with more or fewer lines than {syllable_req_len}.",
    "The {form_name} must not have more or less than {syllable_req_len} lines.",
    "Don't make your {form_name} longer or shorter than {syllable_req_len} lines.",
    "Your {form_name} should strictly adhere to the {syllable_req_len} line requirement.",
    "The {form_name} should neither exceed nor be less than {syllable_req_len} lines.",
    "The {form_name} you write should have exactly {syllable_req_len} lines, no more, no less.",
    "Make sure your {form_name} doesn't have more or less than {syllable_req_len} lines.",
    "The {form_name} should not deviate from the {syllable_req_len} line requirement.",
    "Your {form_name} should not have a line count more or less than {syllable_req_len}.",
    "The {form_name} you write should not be longer or shorter than {syllable_req_len} lines.",
    "The {form_name} should not contain more or fewer lines than the required {syllable_req_len}.",
    "The {form_name} should not have more or less lines than the specified {syllable_req_len}.",
    "The {form_name} should not exceed or fall below the {syllable_req_len} line limit.",
    "The {form_name} should not have a line count exceeding or falling short of {syllable_req_len}.",
    "The {form_name} should not have more or fewer lines than the {syllable_req_len} requirement.",
    "The {form_name} should not have a line count that's more or less than {syllable_req_len}.",
    "The {form_name} should not be longer or shorter than the required {syllable_req_len} lines.",
)

line_number_hn_feedback = (
    "You wrote {observed_num} lines but the poem needs to be have exactly {syllable_req_len} lines.",
    "The poem requires {syllable_req_len} lines, but you've only written {observed_num}.",
    "You've penned {observed_num} lines, however, the poem should contain {syllable_req_len} lines.",
    "The poem should be {syllable_req_len} lines long, but you've only got {observed_num} lines.",
    "You've written {observed_num} lines, but the poem needs exactly {syllable_req_len} lines.",
    "The poem needs to be {syllable_req_len} lines long, but you've only written {observed_num}.",
    "You've only written {observed_num} lines, but the poem needs to be {syllable_req_len} lines.",
    "The poem should have {syllable_req_len} lines, but you've only written {observed_num}.",
    "You've written {observed_num} lines, but the poem should be {syllable_req_len} lines long.",
    "The poem needs {syllable_req_len} lines, but you've written only {observed_num}.",
    "You've only penned {observed_num} lines, but the poem should have {syllable_req_len} lines.",
    "The poem should consist of {syllable_req_len} lines, but you've written {observed_num}.",
    "You've written {observed_num} lines, but the poem needs to consist of {syllable_req_len} lines.",
    "The poem needs to be made up of {syllable_req_len} lines, but you've only written {observed_num}.",
    "You've written {observed_num} lines, but the poem should be made up of {syllable_req_len} lines.",
    "The poem should be {syllable_req_len} lines in length, but you've only written {observed_num}.",
    "You've written {observed_num} lines, but the poem should be {syllable_req_len} lines in length.",
    "The poem needs to have {syllable_req_len} lines, but you've only written {observed_num}.",
    "You've written {observed_num} lines, but the poem needs to have {syllable_req_len} lines.",
    "The poem should contain {syllable_req_len} lines, but you've written {observed_num}.",
    "You've written {observed_num} lines, but the poem should contain {syllable_req_len} lines.",
)

syllable_hn_feedback = (
    "{form_name} needs to have exactly {X} syllables in {syllable_req_len} lines",
    "{form_name} must contain exactly {X} syllables across {syllable_req_len} lines",
    "The {form_name} should be composed of {X} syllables in {syllable_req_len} lines",
    "It's necessary for {form_name} to have {X} syllables in {syllable_req_len} lines",
    "{form_name} requires exactly {X} syllables in {syllable_req_len} lines",
    "The {form_name} must have {X} syllables distributed over {syllable_req_len} lines",
    "The {form_name} needs to consist of {X} syllables in {syllable_req_len} lines",
    "The {form_name} should have {X} syllables spread across {syllable_req_len} lines",
    "The {form_name} must be structured with {X} syllables in {syllable_req_len} lines",
    "The {form_name} needs to be written with {X} syllables in {syllable_req_len} lines",
    "The {form_name} should be formatted with {X} syllables in {syllable_req_len} lines",
    "The {form_name} requires {X} syllables over {syllable_req_len} lines",
    "The {form_name} must be composed of {X} syllables over {syllable_req_len} lines",
    "The {form_name} needs to be structured with {X} syllables over {syllable_req_len} lines",
    "The {form_name} should contain exactly {X} syllables in {syllable_req_len} lines",
    "The {form_name} needs to have {X} syllables spread over {syllable_req_len} lines",
    "The {form_name} must have {X} syllables in {syllable_req_len} lines",
    "The {form_name} should be written with {X} syllables over {syllable_req_len} lines",
    "The {form_name} needs to contain {X} syllables in {syllable_req_len} lines",
    "The {form_name} must be formatted with {X} syllables over {syllable_req_len} lines",
    "The {form_name} should have {X} syllables in {syllable_req_len} lines",
)


syllable_hp_feedback = (
    "These lines are correct because they have the correct syllables: {correct_lines}.",
    "The accuracy of these lines is due to their correct syllable count: {correct_lines}.",
    "These lines are accurate because they contain the right number of syllables: {correct_lines}.",
    "The correctness of these lines is attributed to their proper syllable count: {correct_lines}.",
    "These lines are right because they have the appropriate number of syllables: {correct_lines}.",
    "These lines are correct, thanks to their correct syllable count: {correct_lines}.",
    "The lines are correct because they have the right syllable count: {correct_lines}.",
    "These lines are spot on because they have the correct number of syllables: {correct_lines}.",
    "The lines are accurate because they have the correct syllable count: {correct_lines}.",
    "These lines are precise because they have the correct number of syllables: {correct_lines}.",
    "The lines are correct because they have the appropriate syllable count: {correct_lines}.",
    "These lines are correct because they adhere to the correct syllable count: {correct_lines}.",
    "The lines are correct because they follow the right syllable count: {correct_lines}.",
    "These lines are correct because they match the correct syllable count: {correct_lines}.",
    "The lines are correct because they meet the correct syllable count: {correct_lines}.",
    "These lines are correct because they conform to the correct syllable count: {correct_lines}.",
    "The lines are correct because they comply with the correct syllable count: {correct_lines}.",
    "The lines are correct because they correspond to the correct syllable count: {correct_lines}.",
    "These lines are correct because they fit the correct syllable count: {correct_lines}.",
    "The lines are correct because they align with the correct syllable count: {correct_lines}.",
)

syllable_fp_feedback_1 = (
    "Here are some suggestions to fix your error:",
    "Here's a few recommendations to correct your mistake:",
    "Here's some advice on how to rectify your error:",
    "Here are some tips to help you correct your error:",
    "Here are some proposed solutions to your error:",
    "Here are some ideas on how to fix your mistake:",
    "Here are some pointers to help you resolve your error:",
    "Here are some steps to correct your error:",
    "Here are some guidelines to help you fix your mistake:",
    "Here are some solutions to rectify your error:",
    "Here are some ways to correct your mistake:",
    "Here are some methods to fix your error:",
    "Here are some strategies to help you correct your error:",
    "Here are some instructions to fix your mistake:",
    "Here are some hints to help you rectify your error:",
    "Here are some suggestions to help you resolve your mistake:",
    "Here are some tips to rectify your error:",
    "Here are some recommendations to help you fix your error:",
    "Here are some suggestions to help you correct your error:",
    "Here are some advice to help you fix your mistake:",
    "Here are some suggestions to help you rectify your mistake:",

)


syllable_fp_feedback_2 = (
    'The line: "{line}" has {count} syllables. It should only have {k} syllables. You should rewrite the line to have {improv_direction} syllables.',
    'The sentence: "{line}" contains {count} syllables, but it should only contain {k} syllables. Please revise the sentence to include {improv_direction} syllables.',
    '"{line}" has {count} syllables, which is more than the required {k} syllables. Please adjust the line to have {improv_direction} syllables.',
    'The phrase: "{line}" has {count} syllables, not the {k} syllables it should have. You need to modify the phrase to have {improv_direction} syllables.',
    '"{line}" has {count} syllables, but it needs to have {k} syllables. Please rewrite the line to contain {improv_direction} syllables.',
    'The line: "{line}" has {count} syllables, which is not the required {k} syllables. You need to change the line to have {improv_direction} syllables.',
    '"{line}" has {count} syllables, but it should have {k} syllables. Please adjust the line to include {improv_direction} syllables.',
    'The sentence: "{line}" has {count} syllables, not the {k} syllables it should have. You need to revise the sentence to have {improv_direction} syllables.',
    '"{line}" has {count} syllables, but it needs to have {k} syllables. Please modify the line to contain {improv_direction} syllables.',
    'The phrase: "{line}" has {count} syllables, which is more than the required {k} syllables. You need to change the phrase to have {improv_direction} syllables.',
    '"{line}" has {count} syllables, but it should only contain {k} syllables. Please revise the line to include {improv_direction} syllables.',
    'The line: "{line}" contains {count} syllables, not the {k} syllables it should have. You need to modify the line to have {improv_direction} syllables.',
    '"{line}" has {count} syllables, which is not the required {k} syllables. Please adjust the line to contain {improv_direction} syllables.',
    'The sentence: "{line}" has {count} syllables, but it needs to have {k} syllables. You need to revise the sentence to have {improv_direction} syllables.',
    '"{line}" has {count} syllables, but it should have {k} syllables. Please modify the line to include {improv_direction} syllables.',
    'The phrase: "{line}" contains {count} syllables, but it should only contain {k} syllables. You need to change the phrase to have {improv_direction} syllables.',
    '"{line}" has {count} syllables, which is more than the required {k} syllables. Please revise the line to contain {improv_direction} syllables.',
    'The line: "{line}" has {count} syllables, not the {k} syllables it should have. You need to adjust the line to have {improv_direction} syllables.',
    '"{line}" has {count} syllables, but it needs to have {k} syllables. Please change the line to include {improv_direction} syllables.',
    'The sentence: "{line}" contains {count} syllables, which is not the required {k} syllables. You need to modify the sentence to have {improv_direction} syllables.',
    '"{line}" has {count} syllables, but it should only contain {k} syllables. Please adjust the line to contain {improv_direction} syllables.',
)
