name: 'camel_install'
description: 'Setup python environment and install dependencies for CAMEL using uv.'
inputs:
  python-version:
    description: 'Python version.'
    required: true
    default: '3.10'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '${{ inputs.python-version }}'
    - name: Install uv
      run: |
        pip install uv
      shell: bash
    - name: Setup virtual environment
      run: |
        uv venv .venv --python=${{ inputs.python-version }}
      shell: bash
    - uses: actions/cache/restore@v3
      id: cache-restore
      name: Restore caches for the virtual environment based on uv.lock
      with:
        path: ./.venv
        key: venv-${{ hashFiles('uv.lock') }}
    - name: Install the project dependencies
      run: |
        source .venv/bin/activate
        uv pip install -e ".[all, dev, docs]"
      shell: bash
    - uses: actions/cache/save@v3
      name: Save caches based on uv.lock
      if: ${{ !steps.cache-restore.outputs.cache-hit }}
      with:
        path: ./.venv
        key: venv-${{ hashFiles('uv.lock') }}
