services:
  camel:
    image: camel:localdev
    container_name: camel-localdev
    build:
      context: ../
      dockerfile: .container/Dockerfile
    volumes:
      - ../:/app/camel
    env_file:
      - .env
    user: "${UID:-1000}:${GID:-1000}"
    command: ["tail", "-f", "/dev/null"]


